import { constants, patterns } from '..';
import { industries } from '../industry-option';
export const consultationFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'position',
    label: 'Position',
    type: 'select',
    required: true,
    placeholder: 'e.g. Project Manager',
    section: 'personal',
    options: constants.POSITION,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    pattern: patterns.email,
    section: 'personal',
    maxlength: 254,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    pattern: patterns.phone,
  },
  {
    name: 'companyName',
    label: 'Company Name',
    type: 'text',
    required: false,
    placeholder: 'e.g. JohnDoe and co.',
    section: 'company',
    maxlength: 127,
  },
  {
    name: 'websiteUrl',
    label: 'Company Website',
    type: 'text',
    required: false,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'company',
    maxlength: 100,
  },

  {
    name: 'industry',
    label: 'Industry',
    type: 'select',
    required: false,
    placeholder: 'e.g. Apparel',
    section: 'company',
    options: industries,
  },
  {
    name: 'zipcode',
    label: 'Zip Code',
    type: 'text',
    required: false,
    placeholder: 'e.g. 90001',
    section: 'company',
    maxlength: 25,
  },
  {
    name: 'projectDesc',
    label: 'Project Description',
    type: 'textarea',
    required: false,
    placeholder: 'e.g. Project Description',
    section: 'company',
    maxlength: 1000,
  },
];
