import { patterns } from '..';
export const reconnectFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 're-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 're-2',
    pattern: patterns.phone,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    id: 're-3',
    pattern: patterns.email,
    maxlength: 254,
  },
];
