import { patterns, constants } from '../';
import { industries } from '../industry-option';
export const SDWANFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
  },
  {
    name: 'position',
    label: 'Position',
    type: 'select',
    required: true,
    placeholder: 'e.g. Project Manager',
    options: constants.POSITION,
    section: 'personal',
  },

  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    pattern: patterns.email,
    section: 'personal',
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
  },
  {
    name: 'companyName',
    label: 'Company Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. JohnDoe and co.',
    section: 'company',
  },
  {
    name: 'websiteUrl',
    label: 'Company Website',
    type: 'text',
    required: true,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'company',
  },
  {
    name: 'companySize',
    label: 'Company size',
    type: 'number',
    required: true,
    placeholder: '0',
    section: 'company',
  },
  {
    name: 'industry',
    label: 'Industry',
    type: 'select',
    required: true,
    placeholder: 'e.g. Apparel',
    section: 'company',
    options: industries,
  },
  {
    name: 'sitetype',
    label: 'Site Type',
    type: 'select',
    required: true,
    placeholder: 'e.g. Data Centers',
    options: constants.SITETYPES,
    section: 'location',
  },
  {
    name: 'noofsites',
    label: 'Number of sites',
    type: 'number',
    required: true,
    placeholder: '0',
    options: [],
    section: 'location',
  },
  {
    name: 'primary',
    label: 'Primary',
    type: 'select',
    required: true,
    placeholder: 'e.g. 35 Mbps or less',
    options: constants.PRIMARY,
    section: 'location',
    grouping: true,
  },
  {
    name: 'secondary',
    label: 'Secondary',
    type: 'select',
    required: true,
    placeholder: 'e.g. 35 Mbps',
    options: constants.SECONDARY,
    section: 'location',
    grouping: true,
  },
];
