import { constants, patterns } from '..';

export const signUpFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'sg-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 254,
    id: 'sg-2',
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    required: true,
    placeholder: 'Password',
    section: 'personal',
    maxlength: 50,
    id: 'sg-3',
    pattern: patterns.password,
  },
  {
    name: 'cpassword',
    label: 'Confirm Password',
    type: 'password',
    required: true,
    placeholder: 'Confirm Password',
    section: 'personal',
    maxlength: 50,
    id: 'sg-4',
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'sg-5',
    pattern: patterns.phone,
  },
];

export const userFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'ur-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'lastname',
    label: 'Last Name',
    type: 'text',
    required: false,
    placeholder: 'e.g. Doe',
    section: 'personal',
    pattern: patterns.name,
    maxlength: 75,
  },

  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 254,
    id: 'ur-2',
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'ur-3',
    pattern: patterns.phone,
  },
  {
    name: 'companyName',
    label: 'Company Name',
    type: 'text',
    required: false,
    placeholder: 'e.g. JohnDoe and co.',
    section: 'company',
    maxlength: 127,
  },

  // {
  //   name: 'position',
  //   label: 'Your position in company',
  //   type: 'select',
  //   required: true,
  //   placeholder: 'e.g. Project Manager',
  //   section: 'company',
  //   options: constants.POSITION,
  // },
  {
    name: 'websiteUrl',
    label: 'Current website URL',
    type: 'text',
    required: false,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'company',
    maxlength: 100,
  },
  {
    name: 'nwoOptin',
    label: 'The New World Order™ Opt in',
    type: 'radio',
    required: true,
    id: 'ur-6',
    tooltip: true,
    infoText:
      'The New World Order™ is a global digital community that embraces diversity for the cause of collaborative innovation to create world peace and improve the quality of life for our species. Will you support this cause?',
  },
  {
    name: 'citizenshipOptin',
    label: 'Plurbs Opt in',
    type: 'radio',
    required: true,
    id: 'ur-5',
    tooltip: true,
  },

  {
    name: 'activeEgoOptin',
    label: 'Active-ego™ Opt in',
    type: 'radio',
    required: true,
    id: 'ur-7',
    tooltip: true,
  },
  {
    name: 'wipOptin',
    label: 'World Is My playground™ Opt in',
    type: 'radio',
    required: true,
    id: 'ur-8',
    tooltip: true,
  },
  {
    name: 'climatePushOptin',
    label: 'Climate-push™ Opt in',
    type: 'radio',
    required: true,
    id: 'ur-9',
    tooltip: true,
  },
  {
    name: 'newsletterOptin',
    label: 'Newsletters Opt in',
    type: 'radio',
    required: true,
    id: 'ur-10',
    tooltip: true,
  },
  {
    name: 'emailMarketingOptin',
    label: 'Email Marketing Opt in',
    type: 'radio',
    required: true,
    id: 'ur-11',
    tooltip: true,
  },
];

export const freelancerFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'fl-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'fl-2',
    pattern: patterns.phone,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 254,
    id: 'fl-3',
  },
  {
    name: 'website_url',
    label: 'Current website URL',
    type: 'text',
    required: true,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'personal',
    id: 'fl-8',
  },
  {
    name: 'comment',
    label: 'Describe your application',
    type: 'textarea',
    required: true,
    placeholder: 'e.g. comment',
    maxlength: 1000,
    section: 'personal',
    id: 'fl-9',
  },
];

export const businessUserFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'bu-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'bu-2',
    pattern: patterns.phone,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 254,
    id: 'bu-3',
  },
  {
    name: 'website_url',
    label: 'Current website URL',
    type: 'text',
    required: true,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'personal',
    id: 'bu-8',
  },
  {
    name: 'comment',
    label: 'I commit to being carbon neutral by 2030',
    type: 'textarea',
    required: true,
    placeholder: 'e.g. comment',
    maxlength: 1000,
    section: 'personal',
    id: 'bu-9',
  },
  // {
  //   name: 'companyName',
  //   label: 'Company Name',
  //   type: 'text',
  //   required: true,
  //   placeholder: 'e.g. JohnDoe and co.',
  //   section: 'company',
  //   maxlength: 127,
  //   id: 'bu-4',
  // },

  // {
  //   name: 'companySize',
  //   label: 'Company Size',
  //   type: 'number',
  //   required: true,
  //   placeholder: '0',
  //   section: 'company',
  //   min: 1,
  //   id: 'bu-5',
  // },
  // {
  //   name: 'position',
  //   label: 'Your position in company',
  //   type: 'select',
  //   required: true,
  //   placeholder: 'e.g. Project Manager',
  //   section: 'company',
  //   id: 'bu-6',
  // },
  // {
  //   name: 'websiteUrl',
  //   label: 'Current website URL',
  //   type: 'text',
  //   required: true,
  //   placeholder: 'e.g. https://www.company.com',
  //   pattern: patterns.website_url,
  //   section: 'company',
  //   maxlength: 100,
  //   id: 'bu-7',
  // },
];

export const personalUserFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'pu-1',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'pu-2',
    pattern: patterns.phone,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 254,
    id: 'pu-3',
  },
  {
    name: 'type',
    label: `I'm interested in`,
    type: 'select',
    required: true,
    placeholder: 'e.g. Classess',
    options: constants.INTERESTED,
    id: 'pu-4',
  },
  {
    name: 'goal',
    label: `My Goal is`,
    type: 'select',
    required: true,
    placeholder: 'e.g. Vocational Enablement',
    options: constants.GOALS,
    id: 'pu-4',
  },
  {
    name: 'comment',
    label: 'Additional Comment',
    type: 'textarea',
    required: true,
    placeholder: 'e.g. comment',
    maxlength: 250,
    section: 'personal',
    id: 'bu-9',
  },
  // {
  //   name: 'companyName',
  //   label: 'Company Name',
  //   type: 'text',
  //   required: true,
  //   placeholder: 'e.g. JohnDoe and co.',
  //   section: 'company',
  //   maxlength: 127,
  //   id: 'bu-4',
  // },

  // {
  //   name: 'companySize',
  //   label: 'Company Size',
  //   type: 'number',
  //   required: true,
  //   placeholder: '0',
  //   section: 'company',
  //   min: 1,
  //   id: 'bu-5',
  // },
  // {
  //   name: 'position',
  //   label: 'Your position in company',
  //   type: 'select',
  //   required: true,
  //   placeholder: 'e.g. Project Manager',
  //   section: 'company',
  //   id: 'bu-6',
  // },
  // {
  //   name: 'websiteUrl',
  //   label: 'Current website URL',
  //   type: 'text',
  //   required: true,
  //   placeholder: 'e.g. https://www.company.com',
  //   pattern: patterns.website_url,
  //   section: 'company',
  //   maxlength: 100,
  //   id: 'bu-7',
  // },
];
