import { patterns } from '..';

export const signUpFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    id: 'sg-1',
    maxlength: 100,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    section: 'personal',
    pattern: patterns.email,
    maxlength: 150,
    id: 'sg-2',
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    required: true,
    placeholder: 'Password',
    section: 'personal',
    maxlength: 50,
    id: 'sg-3',
  },
  {
    name: 'cpassword',
    label: 'Confirm Password',
    type: 'password',
    required: true,
    placeholder: 'Confirm Password',
    section: 'personal',
    maxlength: 50,
    id: 'sg-4',
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    id: 'sg-5',
    maxlength: 15,
  },
];
