import { constants, patterns } from '..';
import { industries } from '../industry-option';
export const ucaasFormData = [
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. John',
    section: 'personal',
    pattern: patterns.name,
    maxlength: 75,
  },
  {
    name: 'position',
    label: 'Position',
    type: 'select',
    required: true,
    placeholder: 'e.g. Project Manager',
    section: 'personal',
    options: constants.POSITION,
  },
  {
    name: 'email',
    label: 'E-mail',
    type: 'text',
    required: true,
    placeholder: 'e.g. johndoe@email.com',
    pattern: patterns.email,
    section: 'personal',
    maxlength: 254,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'text',
    required: true,
    placeholder: 'e.g. 123456789',
    section: 'personal',
    pattern: patterns.phone,
  },
  {
    name: 'companyName',
    label: 'Company Name',
    type: 'text',
    required: true,
    placeholder: 'e.g. JohnDoe and co.',
    section: 'company',
    maxlength: 127,
  },
  {
    name: 'websiteUrl',
    label: 'Company Website',
    type: 'text',
    required: true,
    placeholder: 'e.g. https://www.company.com',
    pattern: patterns.website_url,
    section: 'company',
    maxlength: 100,
  },
  {
    name: 'companySize',
    label: 'Company size',
    type: 'number',
    required: true,
    placeholder: '0',
    section: 'company',
    min: 1,
  },
  {
    name: 'industry',
    label: 'Industry',
    type: 'select',
    required: true,
    placeholder: 'e.g. Apparel',
    section: 'company',
    options: industries,
  },
  {
    name: 'addressline1',
    label: 'Business Address',
    type: 'text',
    required: true,
    placeholder: 'e.g. Address line 1',
    section: 'company',
    maxlength: 300,
  },
  {
    name: 'suite',
    label: 'Business Suite Opt.',
    type: 'text',
    required: true,
    placeholder: 'e.g. Suite#1',
    section: 'company',
    maxlength: 100,
  },
  {
    name: 'numberofseats',
    label: 'Number of Seats',
    type: 'number',
    required: true,
    placeholder: 'e.g. 1',
    section: 'company',
    min: 1,
  },
];
